#' Title Get tidy data from results generated by my_vpa
#'
#' @param vpa.res results generated by function my_vpa
#'
#' @return a list contains 1) mod.sel, dataframe with selected variables from function adespatial:foward.sel
#' 2) envfrac.df, explained variation by different environmental matrices
#' @export
#'
#' @examples
get_vpa_df <- function(vpa.res){
  require(vegan)
  # extract results of mod.res
  sp.modes <- vpa.res$mod.res

  # if mod selection is try-error
  none.sel <- data.frame(variables="none",order=NA, R2=NA, R2Cum=NA, AdjR2Cum=NA, F= NA, pvalue=NA)
  if(all(is.na(sp.modes$mod.sel)) ){
    sp.modes$mod.sel <- list(none= none.sel)
  } else if (any((map_chr(sp.modes$mod.sel,class))=="try-error")) {
    nm <- names(sp.modes$mod.sel)
    sp.modes$mod.sel[(map_chr(sp.modes$mod.sel,class))=="try-error"] <- list(none.sel)
    names(sp.modes$mod.sel)[(map_chr(sp.modes$mod.sel,class))=="try-error"] <-  nm[(map_chr(sp.modes$mod.sel,class))=="try-error"]
    

  } else {
    sp.modes$mod.sel <- sp.modes$mod.sel
  }


  # a function to extract selcted variables and explained variations from mod.res (results for my_vpa)
  # mod.res is a list with 5 elements
  # mod, a list, results of CCA or RDA
  # mod.aov, a list, anova results for corresponding mode in mod
  # mod.sel, corresponding selection preocedure for mod list, can be NA, where mod is not significant
  # or an element with class "try-error" i.e., no variable was selected
  # mod.sel.f, a list with selected environmental variables
  # vpa, results of VPA mod
  extract_vpa_df <- function(mod.res){
      mod.sel <- do.call(rbind.data.frame,mod.res$mod.sel) %>%
         mutate(env.type= stringr::word(row.names(.),1,sep="\\.")) %>%
          dplyr::select(8,1:7)
    
    # extract mod selection and explained variation from VPA
    if (all(is.na(mod.res$vpa))){ # for which VPA not succeed
      # means no variable were selected
      # or model is not significant
      

      env.frac <- map_dbl(mod.res$mode,function(mod){
        cat("Extract RsquareAdj (May take minutes if species number is high) \n")
        mod.adjR <- RsquareAdj(mod)
        mod.adjR <- mod.adjR[[2]]
        return(mod.adjR)  })
      envfrac.df <- data.frame(env.type=names(env.frac),
                               adjR2=env.frac,
                               mod.p=map_dbl(mod.res$mod.aov,function(x)x$`Pr(>F)`[1]))


    } else { # for which VPA succeed
      
      env.frac <- mod.res$vpa$part$indfract$Adj.R.square
      if (length(env.frac)==4){ # for varpart(sp, env1, env2)
        envfrac.df <- data.frame(env.type=c(names(mod.res$mod.sel),"Residuals"),
                                 adjR2=env.frac[c(1,3,4)],
                                 mod.p= c((map_dbl(mod.res$mod.aov,function(x)x$`Pr(>F)`[1]))[names(mod.res$mod.sel)],NA))
      } else { # for varpart (sp, env1, env2, env3) and varpart (sp, env1, env2, env3,env4)
        envfrac.df <- data.frame(env.type=c(names(mod.res$mod.sel),"Residuals"),
                                 adjR2=env.frac[1:(length(mod.res$mod.sel)+1)],
                                 mod.p= c((map_dbl(mod.res$mod.aov,function(x)x$`Pr(>F)`[1]))[names(mod.res$mod.sel)],NA))
      }
    }
    return(list(mod.sel=mod.sel, envfrac.df=envfrac.df))

  }
  # For spe based VPA
  if (vpa.res$mod.info$sp.based==T){
    res0 <- map(sp.modes, extract_vpa_df)
    mod.sel.ls <- lapply(res0,'[[',"mod.sel")
    mod.sel.df <- do.call(rbind.data.frame,mod.sel.ls) %>%
      bind_cols(spe=rep(names(mod.sel.ls),map_dbl(mod.sel.ls,nrow)),.)

    envfrac.ls <- lapply(res0,'[[',"envfrac.df")
    envfrac.df <- do.call(rbind.data.frame,envfrac.ls) %>%
      bind_cols(spe=rep(names(envfrac.ls),map_dbl(envfrac.ls,nrow)),.)

    res <- list(mod.sel=mod.sel.df, envfrac.df=envfrac.df)

  } else {
    res <- extract_vpa_df(sp.modes)
  }

  return(res)

}
